force-app/main/default/objects/Account/fields/Total_Paid_Invoice__c.field-meta.xml
<CustomField>
    <fullName>Total_Paid_Invoice__c</fullName>
    <label>Total Paid Invoice</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <required>true</required>
    <deleteConstraint>Restrict</deleteConstraint>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>UnPaid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/apexpractice20NOV2.cls
public class apexpractice20NOV2 {
    public static void invoicerollup(List<Invoice__c> invlist){
        if(invlist.isEmpty())return;
        set<Id> accid=new set<Id>();
        for(Invoice__c inv:invlist){
            if(inv.Account__c!=null && inv.Amount__c!=null){
                accid.add(inv.Account__c);
            }
        }
        
        if(accid.isEmpty()) return;
        
        Map<Id,Decimal> rollupamount=new Map<Id,Decimal>();
        for(AggregateResult arr:[select sum(Amount__c) amt, Account__c accid from Invoice__c where Account__c In:accid And Status__c='Paid' Group By Account__c]){
            rollupamount.put((Id)arr.get('accid'),(Decimal)arr.get('amt'));
        }
        
        List<Account> accnts=new List<Account>();
        for(Id acc:accid){
            Decimal paid_invoice=rollupamount.containsKey(acc)?rollupamount.get(acc):0;
            accnts.add(new Account(Id=acc,Total_Paid_Invoice__c=paid_invoice));
        }
        if(!accnts.isEmpty()){
            update accnts;
        }
        
    }
}